apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:XIg/cwxbV8bPeNiXJ7C+fBo+I7IspXzp9UJPRZHYz0v8JYW1VsUb7/V3kbznL9SHhoZ9VzghO4a//IM7,iv:bSvx/0bOwsu4zquPK7QnTggRjFLHzoqpU4Sf9H5S/4M=,tag:FFwjTvtGTcvFfjgrd5z48A==,type:str]
    admin-user: ENC[AES256_GCM,data:vPNGue7Ruws=,iv:vkZMVwFF4jd4ZTped85WFMdigjmFFdrL/rnUxOYHOXQ=,tag:fRnXabwaTpXfeMZj/xxM3g==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RVY1eWxDcklpSnZMcWpj
            R2JIZG1FdWZ5NWhHY3EveUVWMzdNRXJHaFhrCmRucERpRkIxeVVQQTYxYytUNlEy
            cVNWSXkxNkp6ZE1ocHFOQmRWVGltVVEKLS0tIDlvQkgzaERLMW1EN09nazZkRTZ5
            TDRYc0c4bitnMWlPYUI2R2p2TTRucHcKYX3btog9VzvVrpCTlVq0hIjZ970iSpiL
            5IfAl39mJIvPFQ6eAgtQhNudvG9l6hKNSS8HYfVDddsm3ymsyrCDWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13hphavvlee240rq0j42j60mqxj8s4k9tp473g076xl5z35p8mgjqx29stw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T17:06:05Z"
    mac: ENC[AES256_GCM,data:T124daEgB5hmaDUkyMu49l0fmnOVfdjMwy+kC+ATOi7+/wR0beCPQDsXQK5n04HPYqbqLYYMzyj4PMLRl/23rUdILgSkB8DF2aWOy1rU8Z308fpyoF72kgH8DDfL4d/DVJd4aFsEMXFVnqwjEK6f6OM9p1XZIt2LBoZGdJJHgv4=,iv:8iMiu1O7zkhITjIbLUa5q3KsH8L62stlNra9q1IAMI8=,tag:qyeVSADLSPaP+qksXttvaA==,type:str]
    version: 3.13.3
