apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Thay thế bằng URL git repo thực tế của bạn (hoặc repo local/gitea/gitlab/github)
    repoURL: https://github.com/your-org/gitops-opennebula.git
    targetRevision: HEAD
    path: apps/nginx-demo/base
    plugin:
      name: sops
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
