apiVersion: v1
kind: Secret
metadata:
    name: nginx-demo-secret
    namespace: demo-nginx
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:505K5secXutT2vu4KXkhCqTh2W34kv0=,iv:gWKBTYx3m3O3wB7cATfqpbZla/OCFoNT37JUsvBWDgg=,tag:OReE1N03mzcKf8v2moaCwA==,type:str]
    API_TOKEN: ENC[AES256_GCM,data:0Jj6w1O54oiQqDOCacNIgnIr8f+hqbEwLYj6,iv:B04CIzvtG3iWcgMZFjr82Dtr9b6rVQUiyzidN4L0LnM=,tag:l3PpYaf2WirVExQ+Ve7f6Q==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:TGE4gkw0mGu63WoYpQK/zNDiaWY3je8jH1U=,iv:U8fqBfeVXP4mupA4pyRSZtvCumStxFTGZVV99PNRebs=,tag:fx9EgpPqCj0fC0MjWPry3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRGZLMmtWWWo1TnF3cDZa
            UjRzcElqVUR5TWNsMGM0ZnVpQzk1ZVhXYmlJClpoTGxmWjRhSDhCUTl4M2graVBN
            TVpsdGl2OTdMR0NaQ05YMHRlYk02alUKLS0tIEV2TzdMVEhGL1lML0ovenVWdURQ
            TjFWbloyb2xwc294SWVvR0ZUbDh6dXMKTMmVdKRYCfAp1GrVGeaqRqGClnYWwGoV
            jr5GHqbv5ug1y3TAv3fEt5HgF/NOreIh29W3q3VXTvK+bybMWTlEOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13hphavvlee240rq0j42j60mqxj8s4k9tp473g076xl5z35p8mgjqx29stw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T05:49:49Z"
    mac: ENC[AES256_GCM,data:9qrphSOqTJFh4d13/lnJwNgzdtY7XK7VVDrSQgUjUO8rIGvmaHJxE4rkgRIxTawS0WKQ5z6JYN/lUeTE8UIiSRLjSIN9ANuyI9Cir2ttlcrL8nfFWxLTNPIDSbszgKxtSq/PoLi4dNaxVLZ3Izxn5wu7Q5JmJKJT97aZV2/Xh60=,iv:SlSe6RiToOpeR5q+PCEymrO4L3OiYT7CZuS3n+VdQEw=,tag:ciw4H1C6bwlQ+vdB0hdsLw==,type:str]
    version: 3.13.3
